# Generated by Django 5.0.4 on 2024-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'permissions': [('register_company', 'Can register the company')]},
        ),
        migrations.AddField(
            model_name='empresa',
            name='Empresa_registrada',
            field=models.BooleanField(default=False),
        ),
    ]
