# Generated by Django 5.0.4 on 2024-05-21 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_empresa_registrada_empresa_can_register_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='accountants',
            field=models.ManyToManyField(blank=True, related_name='accountant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rif',
            field=models.CharField(default='v000000000', max_length=10),
        ),
    ]
