# Generated by Django 5.0.4 on 2024-06-01 14:12

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_categoria_producto_pedido_factura_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura_cliente',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura_proveedor',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 1, 14, 12, 58, 656630, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
