# Generated by Django 5.0.4 on 2024-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_remove_factura_cliente_monto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='moneda',
            field=models.CharField(choices=[('Bs', 'Bolivares'), ('$', 'Dolares')], default='Bs', max_length=4),
        ),
    ]
