# Generated by Django 5.0.4 on 2024-06-08 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_producto_moneda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria_producto',
            old_name='descripccion',
            new_name='descripcion',
        ),
    ]
