# Generated by Django 5.0.4 on 2024-06-08 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_rename_descripccion_categoria_producto_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripccion',
            new_name='descripcion',
        ),
    ]
