# Generated by Django 5.0.4 on 2024-06-12 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_rename_descripccion_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria_producto',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
        migrations.AddField(
            model_name='factura_cliente',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
        migrations.AddField(
            model_name='factura_proveedor',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
        migrations.AddField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
    ]
