# Generated by Django 5.0.4 on 2024-06-12 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_categoria_producto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria_producto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
        migrations.AlterField(
            model_name='factura_cliente',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
        migrations.AlterField(
            model_name='factura_proveedor',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.empresa'),
        ),
    ]
